server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-msa-service
          uri: http://localhost:8080/api
          predicates:
            - Path=/api/login, /api/logout, /api/user/**, /api/company/**, /api/oauth/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG