server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  data:
    redis:
      host: 192.0.200.170
      port: 6379
      password: qwer1234
  jwt:
    secret: ${JWT_SECRET}
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/user/**, /api/company/**, /api/delivery/**
        - id: auth-service-route
          uri: lb://auth-service
          predicates:
            - Path=/api/login, /api/logout, /api/oauth/**, /api/auth/**, /api/kakao/**
        - id: order-service-route
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
        - id: board-service-route
          uri: lb://board-service
          predicates:
            - Path=/api/product-boards/**, /api/likes/**, /api/qna/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG