server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  data:
    redis:
      host: 192.168.45.160
      port: 6379
  jwt:
    secret: ${JWT_SECRET}
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: auth-service-route
          uri: lb://auth-service
          predicates:
            - Path=/api/login, /api/logout, /api/oauth/**
        - id: company-service-route
          uri: lb://company-service
          predicates:
            - Path=/api/company/**
        - id: backend-service-route
          uri: lb://backend-service
          predicates:
            - Path=/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG