spring:
  application:
    name: board-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        # default_batch_fetch_size: 15
    database-platform: org.hibernate.dialect.MariaDBDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB

cloud:
  aws:
    s3:
      bucket: ${AWS_BUCKET_NAME}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
      auto: false
    stack:
      auto: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: ${CONTEXT_PATH}

domain: ${DOMAIN}

custom:
  kafka-url: ${KAFKA_URL}
